name: Autonomous Dependency Updater for Pillow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout Experiment Repository
        uses: actions/checkout@v4

      - name: Clone Pillow Repository
        run: git clone https://github.com/python-pillow/Pillow.git

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pip-tools
        run: python -m pip install pip-tools

      - name: Generate requirements.txt using pip-compile
        run: |
          echo "Resolving development dependencies from Pillow's pyproject.toml..."
          
          # Create the input file in the root, pointing to the Pillow project and its "tests" extra.
          echo "-e ./Pillow[tests]" > requirements.in
          
          # --- THE FIX IS HERE: The output file is now in the root directory. ---
          pip-compile --resolver=backtracking --output-file generated-requirements.txt requirements.in

          echo "Generated a complete requirements file:"
          cat generated-requirements.txt

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          # --- And here: the cache is based on the root file. ---
          key: ${{ runner.os }}-pip-${{ hashFiles('generated-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install agent dependencies
        run: pip install google-generativeai pypi-simple packaging

      - name: Update Google AI Library
        run: pip install --upgrade google-generativeai

      - name: Run the Autonomous Agent
        run: python dependency_agent.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      
      - name: Commit and push changes if any
        run: |
          git config --global user.name 'AURA Dependency Agent'
          git config --global user.email 'aura-agent@users.noreply.github.com'
          
          # --- And here: the target file is now the root file. ---
          TARGET_FILE="generated-requirements.txt"
          
          git add $TARGET_FILE
          if git diff-index --quiet HEAD; then
            echo "No dependency changes to commit."
            exit 0
          fi
          
          echo "Dependencies have changed. Committing and pushing..."
          
          COMMIT_BODY="Automated dependency updates for the Pillow library."
          if [ -f metrics_output.txt ]; then
            COMMIT_BODY=$(cat metrics_output.txt)
          fi
          
          git commit -m "chore(deps): Autonomously manage Pillow dependencies [skip ci]" -m "$COMMIT_BODY"
          git push