name: Autonomous Dependency Updater for Pillow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout Experiment Repository
        uses: actions/checkout@v4

      - name: Clone Pillow Repository
        run: git clone https://github.com/python-pillow/Pillow.git

      # --- Pillow-Specific Step 1: Install System Build Dependencies ---
      - name: Install System Dependencies for Pillow Build
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev libtiff5-dev liblcms2-dev libwebp-dev libfreetype6-dev

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pip-tools
        run: python -m pip install pip-tools

      # --- Pillow-Specific Step 2: Generate requirements.txt ---
      - name: Generate requirements.txt using pip-compile
        run: |
          echo "Resolving Pillow's test dependencies from pyproject.toml..."
          echo "-e ./Pillow[tests]" > requirements.in
          # Save the output to the location the agent expects
          pip-compile --resolver=backtracking --output-file generated-requirements.txt requirements.in

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('generated-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install agent dependencies
        run: pip install google-generativeai pypi-simple packaging

      - name: Run the Autonomous Agent
        run: python dependency_agent.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      
      - name: Commit and push changes if any
        run: |
          git config --global user.name 'AURA Dependency Agent'
          git config --global user.email 'aura-agent@users.noreply.github.com'
          
          TARGET_FILE="generated-requirements.txt"
          
          git add $TARGET_FILE
          if git diff-index --quiet HEAD; then
            echo "No dependency changes to commit."
            exit 0
          fi
          
          echo "Dependencies have changed. Committing and pushing..."
          git commit -m "chore(deps): Autonomously manage Pillow dependencies [skip ci]"
          git push